### ISSUE TITLE
I'm getting an error

### ISSUE THREAD

**Issue by harellevy** [alfg/dropdot#6]
When uploading a file using this repo i get an error:
```".write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead."```

my node version is 0.12.4

**Comment by harellevy** [comment]
fixed locally by changing in 
removed
```this.boundary.write('\r\n--', 'ascii', 0);
this.boundary.write(str, 'ascii', 4);```
added instead:
```this.boundary.write('\r\n--', 0, 'ascii');
this.boundary.write(str, 4, 'ascii');```

**Comment by alfg** [comment]
Hi @harellevy, 

Sorry for the late response, but thank you for reporting this. I've just tested a new install of the app on node v.0.12.5, but didn't come across the error above.  

Which version of express.js do you have installed? Dropdot still uses 3.0.6 listed in package.json.

Thanks,
Alf
