### ISSUE TITLE
DreamObjects CORS documentation incorrect

### ISSUE THREAD

**Issue by robbat2** [alfg/dropdot#7]
Your README says that you must upload a cors.xml to set the CORS policy for DreamObjects.

This is incorrect. You must use the S3 cors commands instead. (http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTcors.html)

**Comment by stuartpb** [comment]
This should really be patched - https://help.dreamhost.com/hc/en-us/articles/216201557-How-to-setup-Cross-Origin-Resource-Sharing-CORS-on-DreamObjects lists several different clients and how to use them to set the CORS policy.

**Comment by alfg** [comment]
Sorry for the late response on this. What instructions would you recommend for this project?

PRs also are welcome. :)
