### ISSUE TITLE
unable to upload the file 

### ISSUE THREAD

**Issue by Sikandarkhan** [alfg/dropdot#8]
In console, I am seeing this message. 

**jquery.min.js:5 POST http://****.s3.amazonaws.com/ 400 (Bad Request)**

**Comment by alfg** [comment]
Hi @Sikandarkhan, 

Would you be able to provide more details on your setup and configuration (minus keys of course). I tried setting up the project from scratch again and I didn't come across any new errors.

Make sure to configure the options as described in https://github.com/alfg/dropdot#installation.

**Comment by alfg** [comment]
Closing for now. Feel free to comment/reopen with more details if the problem persists.
