### ISSUE TITLE
Getting Errors

### ISSUE THREAD

**Issue by yonilevine** [alfg/dropdot#9]
Keep getting the following error. Any idea why?

(node:14534) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

Thank you!

**Comment by alfg** [comment]
Ah, there's probably something within the project/libraries that are using an older version that doesn't support the latest Node Buffer API changes. This project is due for an update. :) 

I'll look into this soon.

**Comment by alfg** [comment]
Hi @yonilevine,

I've updated the dependencies and cleaned up a bit on #10. This should resolve the warning you were seeing earlier.

Thanks!
